### PR TITLE
Add 'card' style to sections for readability

### PR DESCRIPTION
**Pull request by j6k4m8**
Needs a quick check by someone with a browser, editing CSS from my phone.

Before:
image

After:
image

### CODE REVIEW

**Comment by jovo** [comment]
i merged.  definitely better, i do wonder about the multiple lines separating each 'card'.
eg, in bluecadet, there are clear separations between sections, but they are implied by the 'card' being the size of the whole window, know what i mean?

**Comment by j6k4m8** [comment]
Not completely sure I follow, but this was all scripted from my phone so
it's possible I missed something obvious.

**Comment by jovo** [comment]
let's talk when you get a chance. i'm on G+ indefinitely...

On Mon, May 25, 2015 at 1:04 PM, Jordan Matelsky notifications@github.com
wrote:

>  Not completely sure I follow, but this was all scripted from my phone so
> it's possible I missed something obvious.
> 
> On Mon, May 25, 2015 at 12:55 PM, joshua vogelstein <
> notifications@github.com> wrote:
> 
> > i merged. definitely better, i do wonder about the multiple lines
> > separating each 'card'.
> > eg, in bluecadet, there are clear separations between sections, but they
> > are implied by the 'card' being the size of the whole window, know what i
> > mean?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jovo/jovo.github.com/pull/19#issuecomment-105268467
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/pull/19#issuecomment-105271032.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
wow that's awesome @j6k4m8 ! how do you do css from your phone?

**Pull request merged**
